# Generated by Django 5.2.6 on 2025-09-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevate', '0004_remove_listing_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='elevate.listing'),
        ),
    ]
