# Generated by Django 5.2.6 on 2025-09-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevate', '0003_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
    ]
